#!/usr/bin/env python
#coding:utf-8

import sys
import translater

import commands
import os
FILE_DIR = os.path.dirname(__file__)
translater_py = os.path.join(FILE_DIR,"translater.py")
prpr_rb = os.path.join(FILE_DIR,"prpr.rb")

def main():
    if len(sys.argv) == 2:
        commands.getoutput("python "+translater_py + " "+sys.argv[1] + "> buf.bas")
        print commands.getoutput("ruby " + prpr_rb + " buf.bas")
    elif len(sys.argv) == 1:
        print commands.getoutput("ruby " + prpr_rb)


if __name__ == "__main__":
    main()
