#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "prpr2.y".
#

require 'racc/parser'



class VarNode
  def initialize(name)
    @name = name
  end
  def eval(var_table)
    return var_table[@name]
  end
end

class NumberNode
  def initialize(value)
    @value = value
  end
  def eval(var_table)
    return @value
  end
end

class StringNode
  def initialize(value)
    @value = value
  end
  def eval(var_table)
    return @value
  end
end

class AddNode
  def initialize(left,right)
    @left = left
    @right = right
  end
  def to_s()
    return "|Add node|\n| #{@left}  #{@right}"
  end
  def eval(var_table)
    return @left.eval(var_table) + @right.eval(var_table)
  end
end

class MinusNode
  def initialize(left,right)
    @left = left
    @right = right
  end
  def to_s()
    return "|Minus node|\n|#{"-"*(@right.to_s.length+2)}|\n#{@left}  #{@right}"
  end
  def eval(var_table)
    return @left.eval(var_table) - @right.eval(var_table)
  end
end

class MultipleNode
  def initialize(left,right)
    @left = left
    @right = right
  end
  def to_s()
    return "|Multiple node|\n|#{"-"*(@right.to_s.length+2)}|\n#{@left}  #{@right}"
  end
  def eval(var_table)
    return @left.eval(var_table) * @right.eval(var_table)
  end
end

class DevNode
  def initialize(left,right)
    @left = left
    @right = right
  end
  def to_s()
    return "|Dev node|\n|#{"-"*(@right.to_s.length+2)}|\n#{@left}  #{@right}"
  end
  def eval(var_table)
    return @left.eval(var_table) / @right.eval(var_table)
  end
end

class ModNode
  def initialize(left,right)
    @left = left
    @right = right
  end
  def to_s()
    return "|Mod node|\n|#{"-"*(@right.to_s.length+2)}|\n#{@left}  #{@right}"
  end
  def eval(var_table)
    @left.eval(var_table)% @right.eval(var_table)
  end
end

class UMinusNode
  def initialize(num)
    @num = num
  end
  def to_s()
    return "|UMinus node|\n|#{@num}"
  end
  def eval(var_table)
    return -1 * @num.eval(var_table)
  end
end

class EqualNode
  def initialize(left,right)
    @left = left
    @right = right
  end
  def to_s()
    return "Mod node\n|#{"-"*(@right.to_s.length+2)}|\n#{@left}  #{@right}"
  end
  def eval(var_table)
    var_table[@left] = @right.eval(var_table)
  end
end

class BoolNode
  def initialize(bool)
    @bool = bool
  end
  def eval(var_table)
    return @bool
  end
end


class IsNode
  def initialize(left,right)
    @left = left
    @right = right
  end
  def eval(var_table)
    return BoolNode.new(@left.eval(var_table)==@right.eval(var_table)).eval(var_table)
  end
end


class BiggerNode
  def initialize(left,right)
    @left = left
    @right = right
  end
  def eval(var_table)
    return BoolNode.new(@left.eval(var_table) > @right.eval(var_node))
  end
end

class IsNotNode
  def initialize(left,right)
    @left = left
    @right = right
  end
  def eval(var_table)
    return BoolNode.new(@left.eval(var_table)!=@right.eval(var_table)).eval(var_table)
  end
end

class IfNode
  def initialize(boolexp,exp)
    @boolexp = boolexp
    @exp = exp
  end
  def eval(var_table)
      b =  @boolexp.eval(var_table)
      puts(b)
      print(b.class)
      if b.class == true.class
        return @exp.eval(var_table)
      else
        raise ParseError
      end
    end
  end

class ForNode
  def initialize(initexp,boolexp,doexp)
    @initexp = initexp
    @boolexp = boolexp
    @doexp = doexp
  end
  def eval(var_table)
    @initexp.eval(var_table)
    while(not @boolexp.eval(var_table))
      @doexp.eval(var_table)
    end
  end
end

class IfElseNode
  def initialize(boolexp,trueexp,falseexp)
    @boolexp = boolexp
    @trueexp = trueexp
    @falseexp = falseexp
  end
  def eval(var_table)
    b = @boolexp.eval(var_table)
    if b.class == true.class
      return @trueexp.eval(var_table)
    elsif b.class == false.class
      return @falseexp.eval(var_table)
    else
      raise ParseError
    end
  end
end

class BlockNode
  def initialize(nodelist)
    @nodelist = nodelist
  end
  def eval(var_table)
    answer = 0
    @nodelist.each do |node|
      answer = node.eval(var_table)
    end
    return answer
  end
end

class PrintNode
  def initialize(value)
    @value = value
  end
  def eval(var_table)
    puts @value.eval(var_table)
  end
end

class Prprp < Racc::Parser

module_eval <<'..end prpr2.y modeval..id9c19f3177c', 'prpr2.y', 282

  def initialize()
    @nodes = []
  end

  def parse(str)
    @q = []
    until str.empty?
      case str
      when /\A\s+/
      when /\A\d+\.?\d*/
        @q.push [:NUMBER, $&.to_f]
      when /\Aif/
        @q.push [:IF,nil]
      when /\Aisnot/
        @q.push [:ISNOT,nil]
      when /\Ais/
        @q.push [:IS,nil]
      when /\Athen/
        @q.push [:THEN,nil]
      when /\Aelse/
        @q.push [:ELSE,nil]
      when /\Aprint/
        @q.push [:PRINT,nil]
      when /\Afor/
        @q.push [:FOR,nil]
      when /\Ato/
        @q.push [:TO,nil]
      when /\Ado/
        @q.push [:DO,nil]
      when /\A"(.*?)"/
        @q.push [:STRING,$1]
      when /\A\w+/
        @q.push [:VAR,$&.to_s]
      when /\A.|\n/o
        s = $&
        @q.push [s, s]
      end
      str = $'
    end
    @q.push [false, '$end']
    do_parse
  end

  def next_token
    @q.shift
  end

..end prpr2.y modeval..id9c19f3177c

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 29, :_reduce_none,
 0, 29, :_reduce_2,
 3, 30, :_reduce_3,
 3, 30, :_reduce_4,
 3, 30, :_reduce_5,
 3, 30, :_reduce_6,
 3, 30, :_reduce_7,
 3, 30, :_reduce_8,
 3, 30, :_reduce_9,
 3, 30, :_reduce_10,
 3, 30, :_reduce_11,
 2, 30, :_reduce_12,
 4, 30, :_reduce_13,
 6, 30, :_reduce_14,
 6, 30, :_reduce_15,
 3, 30, :_reduce_16,
 3, 30, :_reduce_17,
 2, 30, :_reduce_18,
 3, 30, :_reduce_19,
 1, 30, :_reduce_20,
 1, 30, :_reduce_21,
 1, 30, :_reduce_22,
 0, 31, :_reduce_23,
 1, 31, :_reduce_24,
 3, 31, :_reduce_25 ]

racc_reduce_n = 26

racc_shift_n = 53

racc_action_table = [
     7,    17,    31,    21,    22,    23,     2,    15,     5,    19,
    35,     8,    30,   nil,    11,     7,     1,   nil,     3,     4,
     6,     2,   nil,     5,   nil,   nil,     8,   nil,   nil,    11,
     7,     1,   nil,     3,     4,     6,     2,   nil,     5,   nil,
   nil,     8,   nil,   nil,    11,     7,     1,   nil,     3,     4,
     6,     2,   nil,     5,   nil,   nil,     8,   nil,   nil,    11,
     7,     1,   nil,     3,     4,     6,     2,   nil,     5,   nil,
   nil,     8,   nil,   nil,    11,     7,     1,   nil,     3,     4,
     6,     2,   nil,     5,   nil,   nil,     8,   nil,   nil,    11,
     7,     1,   nil,     3,     4,     6,     2,   nil,     5,   nil,
   nil,     8,   nil,   nil,    11,     7,     1,   nil,     3,     4,
     6,     2,   nil,     5,   nil,   nil,     8,   nil,   nil,    11,
     7,     1,   nil,     3,     4,     6,     2,   nil,     5,   nil,
   nil,     8,   nil,   nil,    11,     7,     1,   nil,     3,     4,
     6,     2,   nil,     5,   nil,   nil,     8,   nil,   nil,    11,
     7,     1,   nil,     3,     4,     6,     2,   nil,     5,   nil,
   nil,     8,   nil,   nil,    11,     7,     1,   nil,     3,     4,
     6,     2,   nil,     5,   nil,   nil,     8,   nil,   nil,    11,
     7,     1,   nil,     3,     4,     6,     2,   nil,     5,   nil,
   nil,     8,   nil,   nil,    11,     7,     1,   nil,     3,     4,
     6,     2,   nil,     5,   nil,   nil,     8,   nil,   nil,    11,
     7,     1,   nil,     3,     4,     6,     2,   nil,     5,   nil,
   nil,     8,   nil,   nil,    11,     7,     1,   nil,     3,     4,
     6,     2,   nil,     5,   nil,   nil,     8,   nil,   nil,    11,
     7,     1,   nil,     3,     4,     6,     2,   nil,     5,   nil,
   nil,     8,   nil,   nil,    11,     7,     1,   nil,     3,     4,
     6,     2,   nil,     5,   nil,   nil,     8,   nil,   nil,    11,
     7,     1,   nil,     3,     4,     6,     2,   nil,     5,   nil,
   nil,     8,   nil,   nil,    11,     7,     1,   nil,     3,     4,
     6,     2,   nil,     5,   nil,   nil,     8,   nil,   nil,    11,
     7,     1,   nil,     3,     4,     6,     2,   nil,     5,   nil,
   nil,     8,   nil,   nil,    11,   nil,     1,   nil,     3,     4,
     6,    21,    22,    23,    24,    25,    26,    27,    28,    20,
    21,    22,    23,    24,    25,    26,    27,    28,    20,   nil,
    45,    21,    22,    23,    24,    25,   -26,    50,    21,    22,
    23,    24,    25,    26,    27,    28,    20,    21,    22,    23,
    24,    25,    26,   -26,    34,    21,    22,    23,    24,    25,
    26,    27,    28,    20,    21,    22,    23,   nil,   nil,    49,
    21,    22,    23,    24,    25,    26,    27,    28,    20,   nil,
   nil,   nil,   nil,    33,    21,    22,    23,    24,    25,    26,
    27,    28,    20,    21,    22,    23,    24,    25,    26,    27,
    28,    20,    21,    22,    23,    24,    25,    26,    27,    28,
    20,    21,    22,    23,    24,    25,    26,    27,    28,    20,
    21,    22,    23,    24,    25,    26,    27,    28,   -26,    21,
    22,    23,    24,    25,    26,    27,    28,    20,    21,    22,
    23,    24,    25,    26,    27,    28,    20,    21,    22,    23,
    24,    25,    26,    27,    28,    20,    21,    22,    23,    24,
    25,    26,    27,   -26 ]

racc_action_check = [
     0,     7,    13,    41,    41,    41,     0,     4,     0,     9,
    19,     0,    13,   nil,     0,     1,     0,   nil,     0,     0,
     0,     1,   nil,     1,   nil,   nil,     1,   nil,   nil,     1,
     2,     1,   nil,     1,     1,     1,     2,   nil,     2,   nil,
   nil,     2,   nil,   nil,     2,    50,     2,   nil,     2,     2,
     2,    50,   nil,    50,   nil,   nil,    50,   nil,   nil,    50,
     5,    50,   nil,    50,    50,    50,     5,   nil,     5,   nil,
   nil,     5,   nil,   nil,     5,    49,     5,   nil,     5,     5,
     5,    49,   nil,    49,   nil,   nil,    49,   nil,   nil,    49,
     8,    49,   nil,    49,    49,    49,     8,   nil,     8,   nil,
   nil,     8,   nil,   nil,     8,    34,     8,   nil,     8,     8,
     8,    34,   nil,    34,   nil,   nil,    34,   nil,   nil,    34,
    33,    34,   nil,    34,    34,    34,    33,   nil,    33,   nil,
   nil,    33,   nil,   nil,    33,    11,    33,   nil,    33,    33,
    33,    11,   nil,    11,   nil,   nil,    11,   nil,   nil,    11,
    31,    11,   nil,    11,    11,    11,    31,   nil,    31,   nil,
   nil,    31,   nil,   nil,    31,    28,    31,   nil,    31,    31,
    31,    28,   nil,    28,   nil,   nil,    28,   nil,   nil,    28,
    27,    28,   nil,    28,    28,    28,    27,   nil,    27,   nil,
   nil,    27,   nil,   nil,    27,    15,    27,   nil,    27,    27,
    27,    15,   nil,    15,   nil,   nil,    15,   nil,   nil,    15,
    26,    15,   nil,    15,    15,    15,    26,   nil,    26,   nil,
   nil,    26,   nil,   nil,    26,    23,    26,   nil,    26,    26,
    26,    23,   nil,    23,   nil,   nil,    23,   nil,   nil,    23,
    24,    23,   nil,    23,    23,    23,    24,   nil,    24,   nil,
   nil,    24,   nil,   nil,    24,    20,    24,   nil,    24,    24,
    24,    20,   nil,    20,   nil,   nil,    20,   nil,   nil,    20,
    21,    20,   nil,    20,    20,    20,    21,   nil,    21,   nil,
   nil,    21,   nil,   nil,    21,    22,    21,   nil,    21,    21,
    21,    22,   nil,    22,   nil,   nil,    22,   nil,   nil,    22,
    25,    22,   nil,    22,    22,    22,    25,   nil,    25,   nil,
   nil,    25,   nil,   nil,    25,   nil,    25,   nil,    25,    25,
    25,    29,    29,    29,    29,    29,    29,    29,    29,    29,
    48,    48,    48,    48,    48,    48,    48,    48,    48,   nil,
    29,    42,    42,    42,    42,    42,    42,    48,    18,    18,
    18,    18,    18,    18,    18,    18,    18,    43,    43,    43,
    43,    43,    43,    43,    18,    47,    47,    47,    47,    47,
    47,    47,    47,    47,    40,    40,    40,   nil,   nil,    47,
    16,    16,    16,    16,    16,    16,    16,    16,    16,   nil,
   nil,   nil,   nil,    16,    51,    51,    51,    51,    51,    51,
    51,    51,    51,    32,    32,    32,    32,    32,    32,    32,
    32,    32,    10,    10,    10,    10,    10,    10,    10,    10,
    10,    12,    12,    12,    12,    12,    12,    12,    12,    12,
    36,    36,    36,    36,    36,    36,    36,    36,    36,    14,
    14,    14,    14,    14,    14,    14,    14,    14,    46,    46,
    46,    46,    46,    46,    46,    46,    46,    52,    52,    52,
    52,    52,    52,    52,    52,    52,    44,    44,    44,    44,
    44,    44,    44,    44 ]

racc_action_pointer = [
    -7,     8,    23,   nil,    -5,    53,   nil,   -24,    83,     9,
   409,   128,   418,   -12,   436,   188,   377,   nil,   345,    10,
   248,   263,   278,   218,   233,   293,   203,   173,   158,   318,
   nil,   143,   400,   113,    98,   nil,   427,   nil,   nil,   nil,
   371,     0,   338,   354,   463,   nil,   445,   362,   327,    68,
    38,   391,   454 ]

racc_action_default = [
    -2,   -23,   -26,   -20,   -21,   -26,   -22,   -26,   -26,   -26,
    -1,   -26,   -24,   -26,   -12,   -26,   -26,   -18,   -26,   -26,
   -26,   -26,   -26,   -26,   -26,   -26,   -26,   -26,   -26,   -26,
   -17,   -26,   -19,   -26,   -26,    53,    -9,    -5,    -6,    -7,
    -3,    -4,    -8,   -11,   -10,   -16,   -25,   -13,   -26,   -26,
   -26,   -14,   -15 ]

racc_goto_table = [
    10,    12,    14,     9,    13,    16,   nil,   nil,    18,   nil,
   nil,    29,   nil,   nil,   nil,    32,   nil,   nil,   nil,   nil,
    36,    37,    38,    39,    40,    41,    42,    43,    44,   nil,
   nil,    46,   nil,    47,    48,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    51,
    52 ]

racc_goto_check = [
     2,     2,     2,     1,     3,     2,   nil,   nil,     2,   nil,
   nil,     2,   nil,   nil,   nil,     2,   nil,   nil,   nil,   nil,
     2,     2,     2,     2,     2,     2,     2,     2,     2,   nil,
   nil,     2,   nil,     2,     2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,
     2 ]

racc_goto_pointer = [
   nil,     3,     0,     3 ]

racc_goto_default = [
   nil,   nil,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :UMINUS => 2,
 "*" => 3,
 "/" => 4,
 "%" => 5,
 "+" => 6,
 "-" => 7,
 :IS => 8,
 :ISNOT => 9,
 ">" => 10,
 "<" => 11,
 "=" => 12,
 :PRINT => 13,
 ";" => 14,
 :IF => 15,
 :THEN => 16,
 :ELSE => 17,
 :FOR => 18,
 :TO => 19,
 :DO => 20,
 "(" => 21,
 ")" => 22,
 "{" => 23,
 "}" => 24,
 :NUMBER => 25,
 :VAR => 26,
 :STRING => 27 }

racc_use_result_var = true

racc_nt_base = 28

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'UMINUS',
'"*"',
'"/"',
'"%"',
'"+"',
'"-"',
'IS',
'ISNOT',
'">"',
'"<"',
'"="',
'PRINT',
'";"',
'IF',
'THEN',
'ELSE',
'FOR',
'TO',
'DO',
'"("',
'")"',
'"{"',
'"}"',
'NUMBER',
'VAR',
'STRING',
'$start',
'target',
'exp',
'explist']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

module_eval <<'.,.,', 'prpr2.y', 21
  def _reduce_2( val, _values, result )
 result = NumberNode.new(0)
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 23
  def _reduce_3( val, _values, result )
 result = AddNode.new(val[0],val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 24
  def _reduce_4( val, _values, result )
 result = MinusNode.new(val[0],val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 25
  def _reduce_5( val, _values, result )
 result = MultipleNode.new(val[0],val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 26
  def _reduce_6( val, _values, result )
 result = DevNode.new(val[0],val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 27
  def _reduce_7( val, _values, result )
 result = ModNode.new(val[0],val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 28
  def _reduce_8( val, _values, result )
 result = IsNode.new(val[0],val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 29
  def _reduce_9( val, _values, result )
 result = BiggerNode.new(val[2],val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 30
  def _reduce_10( val, _values, result )
 result = BiggerNode.new(val[0],val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 31
  def _reduce_11( val, _values, result )
 result = IsNotNode.new(val[0],val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 32
  def _reduce_12( val, _values, result )
 result = PrintNode.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 33
  def _reduce_13( val, _values, result )
 result = IfNode.new(val[1],val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 34
  def _reduce_14( val, _values, result )
 result = IfElseNode.new(val[1],val[3],val[5])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 35
  def _reduce_15( val, _values, result )
 result = ForNode.new(val[1],val[3],val[5])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 36
  def _reduce_16( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 37
  def _reduce_17( val, _values, result )
result = BlockNode.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 38
  def _reduce_18( val, _values, result )
 result = UMinusNode.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 39
  def _reduce_19( val, _values, result )
 result = EqualNode.new(val[0],val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 40
  def _reduce_20( val, _values, result )
result = NumberNode.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 41
  def _reduce_21( val, _values, result )
 result = VarNode.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 42
  def _reduce_22( val, _values, result )
 result = StringNode.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 44
  def _reduce_23( val, _values, result )
result = []
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 45
  def _reduce_24( val, _values, result )
result=[val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'prpr2.y', 46
  def _reduce_25( val, _values, result )
result=val[0] << val[2]
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

end   # class Prprp


if ARGV.length == 0
    parser = Prprp.new
    var = {}
    str = ARGF.read
  begin
    parsed = parser.parse(str)
    parsed.eval(var)
  rescue ParseError => e
    puts e
  end
else
    parser = Prprp.new
    var = {}
    f = open(ARGV[0])
    begin
      str = f.read
      parsed = parser.parse(str)
      parsed.eval(var)
    rescue ParseError => e
      puts e
    end
    f.close()
end
